weapons.Register({
	Author = "Sadoku",
	Instructions = "Left click fire, right click zoom",
	Contact = "",
	Purpose = "",
	PrintName = "Ak",
	Slot = 3,
	SlotPos = 1,
	IconLetter = "b",
	DrawCrosshair = true,
	Base = "weapon_cs_base",
	Category = "Gleipnir",
	Spawnable = true,
	AdminSpawnable = true,
	ViewModel = "models/weapons/v_rif_ak47.mdl",
	WorldModel = "models/weapons/w_rif_ak47.mdl",
	Weight = 5,
	AutoSwitchTo = false,
	AutoSwitchFrom = false,
	Primary.Sound = Sound( "Weapon_AK47.Single" ),
	Primary.Recoil = 1.5,
	Primary.Damage = 40,
	Primary.NumShots = 1,
	Primary.Cone = 0.02,
	Primary.ClipSize = 25,
	Primary.Delay = 0.07,
	Primary.DefaultClip = 50,
	Primary.Automatic = true,
	Primary.Ammo = "smg1",
	Secondary.Automatic = false,
	Secondary.Ammo = "none",
	IronSightsPos = Vector( 6.1, -7, 2.5 ),
	IronSightsAng = Vector( 2.8, 0, 0 ),
	Initialize = function(self)
		self:SetWeaponHoldType("ar2")
	end,
end
}, "ak47", true)
